language: node_js
node_js:
  - node
sudo: required
services:
  - docker
script:
  - lerna bootstrap
  # lint
  - npm run lint
  # transpile to js
  - lerna run build
  # start docker environment for tests
  - docker-compose up -d
  # run tests with coverage report
  - npm run test-cover
  # submit coverage report
  - npm run test-cover-submit
